=== NRobert-jmdrgg/JMDRGG_XMLgyak/jmdrgg_1012/XMLSchemajmdrgg.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <!-- Egyszerű típusok -->
  <xs:simpleType name="csillagType">
    <xs:restriction base="xs:int">
      <xs:enumeration value="1" />
      <xs:enumeration value="2" />
      <xs:enumeration value="3" />
      <xs:enumeration value="4" />
      <xs:enumeration value="5" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="eletkorType">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="16" />
      <xs:maxInclusive value="120" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="osszegType">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="1" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Egyszerű egyedek -->
  <xs:element name="csillag" type="csillagType" />
  <xs:element name="varos" type="xs:string" />
  <xs:element name="utca" type="xs:string" />
  <xs:element name="hazszam" type="xs:string" />
  <xs:element name="nev" type="xs:string" />
  <xs:element name="eletkor" type="eletkorType" />
  <xs:element name="reszleg" type="xs:string" />
  <xs:element name="vegzettseg" type="xs:string" />
  <xs:element name="osszeg" type="osszegType" />
  <xs:element name="etel" type="xs:string" />
  <xs:element name="kezdete" type="xs:string" />
  <xs:element name="idotartama" type="xs:string" />
  <xs:element name="muszak" type="xs:string" />

  <!-- Attributumok -->
  <xs:attribute name="ekod" type="xs:string" />
  <xs:attribute name="fkod" type="xs:string" />
  <xs:attribute name="gykod" type="xs:string" />
  <xs:attribute name="szkod" type="xs:string" />
  <xs:attribute name="vkod" type="xs:string" />
  <xs:attribute name="e_f" type="xs:string" />
  <xs:attribute name="v_r" type="xs:string" />
  <xs:attribute name="e_r" type="xs:string" />
  <xs:attribute name="e_gy" type="xs:string" />
  <xs:attribute name="e_sz" type="xs:string" />

  <!-- Komplex egyedek -->
  <xs:element name="cim">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="varos" />
        <xs:element ref="utca" />
        <xs:element ref="hazszam" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="gyakorlat">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="kezdete" />
        <xs:element ref="idotartama" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="etterem">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="csillag" minOccurs="1" maxOccurs="1" />
        <xs:element ref="cim" />
        <xs:element ref="nev" minOccurs="1" maxOccurs="1" />
      </xs:sequence>
      <xs:attribute ref="ekod" use="required"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="foszakacs">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nev" minOccurs="1" maxOccurs="1" />
        <xs:element ref="eletkor" />
        <xs:element ref="vegzettseg" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute ref="fkod" use="required" />
      <xs:attribute ref="e_f" />
    </xs:complexType>
    
  </xs:element>

  <xs:element name="vendeg">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nev" minOccurs="1" maxOccurs="1" />
        <xs:element ref="eletkor" />
        <xs:element ref="cim" />
      </xs:sequence>
      <xs:attribute ref="vkod" use="required" />
    </xs:complexType>
    
  </xs:element>

  <xs:element name="rendeles">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="osszeg" />
        <xs:element ref="etel" />
      </xs:sequence>
      <xs:attribute ref="e_r" />
      <xs:attribute ref="v_r" />
    </xs:complexType>
    
  </xs:element>

  <xs:element name="gyakornok">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nev" minOccurs="1" maxOccurs="1" />
        <xs:element ref="gyakorlat" />
        <xs:element ref="muszak" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute ref="gykod" use="required" />
      <xs:attribute ref="e_gy" />
    </xs:complexType>
    
  </xs:element>
  
  <xs:element name="szakacs">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nev" minOccurs="1" maxOccurs="1" />
        <xs:element ref="reszleg" />
        <xs:element ref="vegzettseg" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute ref="szkod" use="required" />
      <xs:attribute ref="e_sz" />
    </xs:complexType>
    
  </xs:element>

  <!-- gyökér elem -->
  <xs:element name="NR_vendeglatas">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="etterem" maxOccurs="unbounded" />
        <xs:element ref="foszakacs" maxOccurs="unbounded" />
        <xs:element ref="vendeg" maxOccurs="unbounded" />
        <xs:element ref="gyakornok" maxOccurs="unbounded" />
        <xs:element ref="szakacs" maxOccurs="unbounded" />
        <xs:element ref="rendeles" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
    
    <xs:key name="etteremKey">
      <xs:selector xpath="etterem" />
      <xs:field xpath="@ekod" />
    </xs:key>
    <xs:key name="foszakacsKey">
      <xs:selector xpath="foszakacs" />
      <xs:field xpath="@fkod" />
    </xs:key>
    <xs:key name="vendegKey">
      <xs:selector xpath="vendeg" />
      <xs:field xpath="@vkod" />
    </xs:key>
    <xs:key name="gyakornokKey">
      <xs:selector xpath="gyakornok" />
      <xs:field xpath="@gykod" />
    </xs:key>
    <xs:key name="szakacsKey">
      <xs:selector xpath="szakacs" />
      <xs:field xpath="@szkod" />
    </xs:key>
    <xs:keyref refer="etteremKey" name="etteremForeignKey">
      <xs:selector xpath="rendeles" />
      <xs:field xpath="@e_r" />
    </xs:keyref>
    <xs:keyref refer="vendegKey" name="vendegForeignKey">
      <xs:selector xpath="rendeles" />
      <xs:field xpath="@v_r" />
    </xs:keyref>
    <xs:keyref refer="etteremKey" name="foszakacsForeignKey">
      <xs:selector xpath="etterem" />
      <xs:field xpath="@e_f" />
    </xs:keyref>
    <xs:keyref refer="etteremKey" name="szakacsForeignKey">
      <xs:selector xpath="etterem" />
      <xs:field xpath="@e_sz" />
    </xs:keyref>
    <xs:keyref refer="etteremKey" name="gyakornokForeignKey">
      <xs:selector xpath="etterem" />
      <xs:field xpath="@e_gy" />
    </xs:keyref>
  </xs:element>
</xs:schema>

=== NRobert-jmdrgg/JMDRGG_XMLgyak/jmdrgg_1012/XMLjmdrgg.xml
<?xml version="1.0" encoding="UTF-8"?>

<NR_vendeglatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="XMLSchemajmdrgg.xsd">
  <etterem ekod="e1">
    <csillag>2</csillag>
    <cim>
      <varos>Miskolc</varos>
      <utca>Egyetem</utca>
      <hazszam>42069</hazszam>
    </cim>
    <nev>Gasztromuhely</nev>
  </etterem>
  <etterem ekod="e2">
    <csillag>1</csillag>
    <cim>
      <varos>Túrkeve</varos>
      <utca>Kossuth</utca>
      <hazszam>15</hazszam>
    </cim>
    <nev>Keve étterem</nev>
  </etterem>
  <etterem ekod="e3">
    <csillag>4</csillag>
    <cim>
      <varos>Tiszafüred</varos>
      <utca>Fő</utca>
      <hazszam>8</hazszam>
    </cim>
    <nev>Nemzeti étterem</nev>
  </etterem>

  <foszakacs fkod="f1" e_f="e1">
    <nev>Carl Brutananadilewski</nev>
    <eletkor>61</eletkor>
    <vegzettseg>Érettségi</vegzettseg>
  </foszakacs>
  <foszakacs fkod="f2" e_f="e2">
    <nev>Dean Takahashi</nev>
    <eletkor>48</eletkor>
    <vegzettseg>Érettségi</vegzettseg>
    <vegzettseg>Egyetem</vegzettseg>
  </foszakacs>
  <foszakacs fkod="f3" e_f="e3">
    <nev>Richard Samuel Jordan</nev>
    <eletkor>32</eletkor>
    <vegzettseg>Érettségi</vegzettseg>
    <vegzettseg>Egyetem</vegzettseg>
    <vegzettseg>Phd</vegzettseg>
  </foszakacs>

  <vendeg vkod="v1">
    <nev>Jeb Bush</nev>
    <eletkor>69</eletkor>
    <cim>
      <varos>Midland</varos>
      <utca>Street</utca>
      <hazszam>213</hazszam>
    </cim>
  </vendeg>
  <vendeg vkod="v2">
    <nev>Samir Al-Hajeed</nev>
    <eletkor>37</eletkor>
    <cim>
      <varos>New York</varos>
      <utca>Greenwich</utca>
      <hazszam>180</hazszam>
    </cim>
  </vendeg>
  <vendeg vkod="v3">
    <nev>Mogusa Shirose</nev>
    <eletkor>26</eletkor>
    <cim>
      <varos>Nuuk</varos>
      <utca>Singoriaq</utca>
      <hazszam>55</hazszam>
    </cim>
  </vendeg>

  <gyakornok gykod="gy1" e_gy="e1">
    <nev>Dalauan Sparrow</nev>
    <gyakorlat>
      <kezdete>2006-06-24</kezdete>
      <idotartama>5 hónap</idotartama>
    </gyakorlat>
    <muszak>Délutáni</muszak>
  </gyakornok>
  <gyakornok gykod="gy2" e_gy="e2">
    <nev>Andrew Jackerry Jacked</nev>
    <gyakorlat>
      <kezdete>2019-12-01</kezdete>
      <idotartama>1 hónap</idotartama>
    </gyakorlat>
    <muszak>Esti</muszak>
    <muszak>Délutáni</muszak>
  </gyakornok>
  <gyakornok gykod="gy3" e_gy="e3">
    <nev>Dick Assman</nev>
    <gyakorlat>
      <kezdete>1986-02-14</kezdete>
      <idotartama>6 hónap</idotartama>
    </gyakorlat>
    <muszak>Délelötti</muszak>
  </gyakornok>

  <szakacs szkod="sz1" e_sz="e3">
    <nev>Bartos Cs. István</nev>
    <reszleg>Kóstoló</reszleg>
    <vegzettseg>Érettségi</vegzettseg>
    <vegzettseg>Egyetem</vegzettseg>
  </szakacs>
  <szakacs szkod="sz2" e_sz="e3">
    <nev>Kim Il-Sung</nev>
    <reszleg>Krumpli pucoló</reszleg>
    <vegzettseg>Érettségi</vegzettseg>
  </szakacs>
  <szakacs szkod="sz3" e_sz="e2">
    <nev>Hannibal Lecter</nev>
    <reszleg>Daraboló</reszleg>
    <vegzettseg>Érettségi</vegzettseg>
    <vegzettseg>Egyetem</vegzettseg>
    <vegzettseg>Phd</vegzettseg>
  </szakacs>

  <rendeles e_r="e1" v_r="v1">
    <osszeg>3100</osszeg>
    <etel>2 darab akciós menü</etel>
  </rendeles>
  <rendeles e_r="e2" v_r="v2">
    <osszeg>1400</osszeg>
    <etel>Magyaros bableves</etel>
  </rendeles>
  <rendeles e_r="e3" v_r="v3">
    <osszeg>1600</osszeg>
    <etel>Húsleves hús nélkül</etel>
  </rendeles>
</NR_vendeglatas>
