=== NRobert-jmdrgg/JMDRGG_XMLgyak/XMLTaskJmdrgg/XMLSchemaJmdrgg.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- egyszeru tipusok -->
  <xs:simpleType name="torzsvasarlo_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="igen"></xs:enumeration>
      <xs:enumeration value="nem"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="eletkor_type">
    <xs:restriction base="xs:int">
      <xs:minExclusive value="0" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="nem_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="nő" />
      <xs:enumeration value="férfi" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ar_type">
    <xs:restriction base="xs:int">
      <xs:minExclusive value="0" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="kaloria_type">
    <xs:restriction base="xs:int">
      <xs:minExclusive value="0" />
      <xs:maxInclusive value="4000" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ertekeles_type">
    <xs:restriction base="xs:float">
      <xs:minInclusive value="1" />
      <xs:maxInclusive value="10" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="weboldal_type">
    <xs:restriction base="xs:string">
      <xs:pattern value="[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z]{1,6}" />
    </xs:restriction>
  </xs:simpleType>

  <!-- attributumok -->
  <xs:attribute name="v_id" type="xs:NCName" />
  <xs:attribute name="v_t" type="xs:NCName" />
  <xs:attribute name="s_t" type="xs:NCName" />
  <xs:attribute name="s_id" type="xs:NCName" />
  <xs:attribute name="s_sl" type="xs:NCName" />
  <xs:attribute name="sl_id" type="xs:NCName" />
  <xs:attribute name="sl_c" type="xs:NCName" />
  <xs:attribute name="c_id" type="xs:NCName" />
  <xs:attribute name="cu_id" type="xs:NCName" />
  <xs:attribute name="cu_c" type="xs:NCName" />

  <!-- egyszeru egyedek -->
  <xs:element name="keresztnev" type="xs:string" />
  <xs:element name="vezeteknev" type="xs:string" />
  <xs:element name="torzsvasarlo" type="torzsvasarlo_type" default="nem" />
  <xs:element name="eletkor" type="eletkor_type" />
  <xs:element name="nem" type="nem_type" default="nő" />
  <xs:element name="datum" type="xs:date" />
  <xs:element name="ar" type="ar_type" />
  <xs:element name="tulajdonsag" type="xs:string" />
  <xs:element name="kaloria" type="kaloria_type" />
  <xs:element name="nev" type="xs:string" />
  <xs:element name="varos" type="xs:string" />
  <xs:element name="utca" type="xs:string" />
  <xs:element name="hazszam" type="xs:string" />
  <xs:element name="legnepszerubb" type=" xs:string" />
  <xs:element name="legnepszerutlenebb" type=" xs:string" />
  <xs:element name="legutobb_frissitve" type=" xs:date" />
  <xs:element name="ertekeles" type=" ertekeles_type" />
  <xs:element name="tulajdonos" type=" xs:string" />
  <xs:element name="weboldal" type=" weboldal_type" />

  <!-- komplex tipusok -->
  <xs:complexType name="nev_type">
    <xs:sequence>
      <xs:element ref="vezeteknev" />
      <xs:element ref="keresztnev" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="hely_type">
    <xs:sequence>
      <xs:element ref="varos" />
      <xs:element ref="utca" />
      <xs:element ref="hazszam" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="vasarlo_type">
    <xs:sequence>
      <xs:element name="nev" type="nev_type" />
      <xs:element ref="torzsvasarlo" />
      <xs:element ref="eletkor" />
      <xs:element ref="nem" />
    </xs:sequence>
    <xs:attribute ref="v_id" use="required" />
  </xs:complexType>

  <xs:complexType name="tranzakcio_type">
    <xs:sequence>
      <xs:element ref="datum" />
    </xs:sequence>
    <xs:attribute ref="v_t" use="required" />
    <xs:attribute ref="s_t" use="required" />
  </xs:complexType>

  <xs:complexType name="sutemeny_type">
    <xs:sequence>
      <xs:element ref="nev" />
      <xs:element ref="ar" />
      <xs:element ref="kaloria" />
      <xs:element ref="tulajdonsag" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute ref="s_id" use="required" />
    <xs:attribute ref="s_sl" use="required" />
  </xs:complexType>

  <xs:complexType name="sutemeny_lista_type">
    <xs:sequence>
      <xs:element ref="legnepszerubb" />
      <xs:element ref="legnepszerutlenebb" />
      <xs:element ref="legutobb_frissitve" minOccurs="1" />
    </xs:sequence>
    <xs:attribute ref="sl_id" use="required" />
    <xs:attribute ref="sl_c" use="required" />
  </xs:complexType>

  <xs:complexType name="cukraszda_type">
    <xs:sequence>
      <xs:element ref="nev" minOccurs="1" />
      <xs:element name="hely" type="hely_type" minOccurs="1" />
      <xs:element ref="ertekeles" />
      <xs:element ref="tulajdonos" />
      <xs:element ref="weboldal" />
    </xs:sequence>
    <xs:attribute ref="c_id" use="required" />
  </xs:complexType>

  <xs:complexType name="cukrasz_type">
    <xs:sequence>
      <xs:element name="nev" type="nev_type" minOccurs="1" />
      <xs:element ref="eletkor" />
      <xs:element ref="nem" />
    </xs:sequence>
    <xs:attribute ref="cu_id" use="required" />
    <xs:attribute ref="cu_c" use="required" />
  </xs:complexType>

  <!-- root -->
  <xs:element name="NR_beadando">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="cukraszda" type="cukraszda_type" minOccurs="1" maxOccurs="unbounded" />
        <xs:element name="cukrasz" type="cukrasz_type" minOccurs="1" maxOccurs="unbounded" />
        <xs:element name="sutemeny_lista" type="sutemeny_lista_type" minOccurs="1" maxOccurs="unbounded" />
        <xs:element name="sutemeny" type="sutemeny_type" minOccurs="1" maxOccurs="unbounded" />
        <xs:element name="vasarlo" type="vasarlo_type" minOccurs="1" maxOccurs="unbounded" />
        <xs:element name="tranzakcio" type="tranzakcio_type" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
    <!-- kulcsok -->

    <xs:key name="cukraszda_key">
      <xs:selector xpath="cukraszda" />
      <xs:field xpath="@c_id" />
    </xs:key>

    <xs:keyref name="cukrasz_cukraszda_key" refer="cukraszda_key">
      <xs:selector xpath="cukrasz" />
      <xs:field xpath="@cu_c" />
    </xs:keyref>

    <xs:keyref name="sutemeny_lista_cukraszda_key" refer="cukraszda_key">
      <xs:selector xpath="sutemeny_lista" />
      <xs:field xpath="@sl_c" />
    </xs:keyref>

    <xs:key name="sutemeny_lista_key">
      <xs:selector xpath="sutemeny_lista" />
      <xs:field xpath="@sl_id" />
    </xs:key>

    <xs:keyref name="sutemeny_sutemeny_lista_key" refer="sutemeny_lista_key">
      <xs:selector xpath="sutemeny" />
      <xs:field xpath="@s_sl" />
    </xs:keyref>

    <xs:key name="vasarlo_key">
      <xs:selector xpath="vasarlo" />
      <xs:field xpath="@v_id" />
    </xs:key>

    <xs:keyref name="vasarlo_tranzakcio_key" refer="vasarlo_key">
      <xs:selector xpath="tranzakcio" />
      <xs:field xpath="@v_t"></xs:field>
    </xs:keyref>

    <xs:key name="sutemeny_key">
      <xs:selector xpath="sutemeny" />
      <xs:field xpath="@s_id" />
    </xs:key>

    <xs:keyref name="sutemeny_tranzakcio_key" refer="sutemeny_key">
      <xs:selector xpath="tranzakcio" />
      <xs:field xpath="@s_t"></xs:field>
    </xs:keyref>

  </xs:element>
</xs:schema>

=== NRobert-jmdrgg/JMDRGG_XMLgyak/XMLTaskJmdrgg/DOMParseJmdrgg/XMLjmdrgg.xml
<?xml version="1.0" encoding="UTF-8"?>
<NR_beadando xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaJmdrgg.xsd">
  <cukraszda c_id="c1">
    <nev>Daubner Cukrászda</nev>
    <hely>
      <varos>Budapest</varos>
      <utca>Szépvölgyi </utca>
      <hazszam>50</hazszam>
    </hely>
    <ertekeles>4.3</ertekeles>
    <tulajdonos>Pista Laci</tulajdonos>
    <weboldal>daubnercukraszda.hu</weboldal>
  </cukraszda>
  <cukraszda c_id="c2">
    <nev>Frey Cukrászda</nev>
    <hely>
      <varos>Pécs</varos>
      <utca>Hungária</utca>
      <hazszam>53/1</hazszam>
    </hely>
    <ertekeles>4.7</ertekeles>
    <tulajdonos>Rotyis Bálint</tulajdonos>
    <weboldal>freycukraszda.hu</weboldal>
  </cukraszda>
  <cukraszda c_id="c3">
    <nev>Szűőke cukrászda</nev>
    <hely>
      <varos>Debrecen</varos>
      <utca>Úrrétje</utca>
      <hazszam>14</hazszam>
    </hely>
    <ertekeles>4.5</ertekeles>
    <tulajdonos>Szőke Balázs</tulajdonos>
    <weboldal>szokecukraszda.hu</weboldal>
  </cukraszda>
  <cukrasz cu_c="c1" cu_id="cu1">
    <nev>
      <vezeteknev>Tompa</vezeteknev>
      <keresztnev>Tamás</keresztnev>
    </nev>
    <eletkor>57</eletkor>
    <nem>férfi</nem>
  </cukrasz>
  <cukrasz cu_c="c1" cu_id="cu2">
    <nev>
      <vezeteknev>Patkós</vezeteknev>
      <keresztnev>Petra</keresztnev>
    </nev>
    <eletkor>21</eletkor>
    <nem>nő</nem>
  </cukrasz>
  <cukrasz cu_c="c1" cu_id="cu3">
    <nev>
      <vezeteknev>Nagy</vezeteknev>
      <keresztnev>Bence</keresztnev>
    </nev>
    <eletkor>18</eletkor>
    <nem>férfi</nem>
  </cukrasz>
  <cukrasz cu_c="c2" cu_id="cu4">
    <nev>
      <vezeteknev>Szabó</vezeteknev>
      <keresztnev>Bence</keresztnev>
    </nev>
    <eletkor>21</eletkor>
    <nem>férfi</nem>
  </cukrasz>
  <cukrasz cu_c="c2" cu_id="cu5">
    <nev>
      <vezeteknev>Mathers</vezeteknev>
      <keresztnev>Marshall</keresztnev>
    </nev>
    <eletkor>50</eletkor>
    <nem>férfi</nem>
  </cukrasz>
  <cukrasz cu_c="c2" cu_id="cu6">
    <nev>
      <vezeteknev>Jepsen</vezeteknev>
      <keresztnev>Carly</keresztnev>
    </nev>
    <eletkor>36</eletkor>
    <nem>nő</nem>
  </cukrasz>
  <cukrasz cu_c="c3" cu_id="cu7">
    <nev>
      <vezeteknev>Snake</vezeteknev>
      <keresztnev>David</keresztnev>
    </nev>
    <eletkor>24</eletkor>
    <nem>férfi</nem>
  </cukrasz>
  <cukrasz cu_c="c3" cu_id="cu8">
    <nev>
      <vezeteknev>McMillen</vezeteknev>
      <keresztnev>Edmund</keresztnev>
    </nev>
    <eletkor>42</eletkor>
    <nem>férfi</nem>
  </cukrasz>
  <cukrasz cu_c="c3" cu_id="cu9">
    <nev>
      <vezeteknev>Fors</vezeteknev>
      <keresztnev>Sebastian</keresztnev>
    </nev>
    <eletkor>31</eletkor>
    <nem>férfi</nem>
  </cukrasz>
  <sutemeny_lista sl_c="c1" sl_id="sl1">
    <legnepszerubb>Mignon</legnepszerubb>
    <legnepszerutlenebb>Almás pite</legnepszerutlenebb>
    <legutobb_frissitve>2022-04-26</legutobb_frissitve>
  </sutemeny_lista>
  <sutemeny_lista sl_c="c2" sl_id="sl2">
    <legnepszerubb>Képviselőfánk</legnepszerubb>
    <legnepszerutlenebb>Piskótatekercs</legnepszerutlenebb>
    <legutobb_frissitve>2022-06-22</legutobb_frissitve>
  </sutemeny_lista>
  <sutemeny_lista sl_c="c3" sl_id="sl3">
    <legnepszerubb>Joghurtos epertorta szelet</legnepszerubb>
    <legnepszerutlenebb>Somlói galuska</legnepszerutlenebb>
    <legutobb_frissitve>2022-03-20</legutobb_frissitve>
  </sutemeny_lista>
  <sutemeny s_id="s2" s_sl="sl1">
    <nev>Mandarinos túrótorta szelet</nev>
    <ar>990</ar>
    <kaloria>360</kaloria>
    <tulajdonsag>csokoládés piskóta</tulajdonsag>
    <tulajdonsag>gyümölcsös</tulajdonsag>
    <tulajdonsag>klasszikus tortaszelet</tulajdonsag>
    <tulajdonsag>tejszínes</tulajdonsag>
    <tulajdonsag>torta szelet</tulajdonsag>
    <tulajdonsag>túrós</tulajdonsag>
  </sutemeny>
  <sutemeny s_id="s3" s_sl="sl1">
    <nev>Cukormentes málnatorta szelet</nev>
    <ar>860</ar>
    <kaloria>200</kaloria>
    <tulajdonsag>Cukormentes </tulajdonsag>
    <tulajdonsag>málnás</tulajdonsag>
    <tulajdonsag>Mandulás</tulajdonsag>
    <tulajdonsag>piskóta</tulajdonsag>
    <tulajdonsag>torta szelet</tulajdonsag>
  </sutemeny>
  <sutemeny s_id="s10" s_sl="sl3">
    <nev>Somlói galuska</nev>
    <ar>1100</ar>
    <kaloria>450</kaloria>
    <tulajdonsag>csokoládé öntet</tulajdonsag>
    <tulajdonsag>Csokoládés</tulajdonsag>
    <tulajdonsag>mazsolás</tulajdonsag>
    <tulajdonsag>piskóta</tulajdonsag>
    <tulajdonsag>tejszínhabos</tulajdonsag>
  </sutemeny>
  <vasarlo v_id="v1">
    <nev>
      <vezeteknev>Nagy</vezeteknev>
      <keresztnev>Pista</keresztnev>
    </nev>
    <torzsvasarlo>igen</torzsvasarlo>
    <eletkor>21</eletkor>
    <nem>férfi</nem>
  </vasarlo>
  <vasarlo v_id="v2">
    <nev>
      <vezeteknev>Sándor</vezeteknev>
      <keresztnev>Béla</keresztnev>
    </nev>
    <torzsvasarlo>nem</torzsvasarlo>
    <eletkor>26</eletkor>
    <nem>nő</nem>
  </vasarlo>
  <vasarlo v_id="v3">
    <nev>
      <vezeteknev>Ferenc</vezeteknev>
      <keresztnev>Viktor</keresztnev>
    </nev>
    <torzsvasarlo>nem</torzsvasarlo>
    <eletkor>56</eletkor>
    <nem>férfi</nem>
  </vasarlo>
  <tranzakcio s_t="s1" v_t="v1">
    <datum>2022-03-20</datum>
  </tranzakcio>
  <tranzakcio s_t="s2" v_t="v1">
    <datum>2022-03-20</datum>
  </tranzakcio>
  <tranzakcio s_t="s4" v_t="v1">
    <datum>2022-04-01</datum>
  </tranzakcio>
  <tranzakcio s_t="s5" v_t="v1">
    <datum>2022-04-01</datum>
  </tranzakcio>
  <tranzakcio s_t="s9" v_t="v1">
    <datum>2022-04-01</datum>
  </tranzakcio>
  <tranzakcio s_t="s2" v_t="v2">
    <datum>2022-04-12</datum>
  </tranzakcio>
  <tranzakcio s_t="s1" v_t="v2">
    <datum>2022-04-12</datum>
  </tranzakcio>
  <tranzakcio s_t="s4" v_t="v2">
    <datum>2022-05-02</datum>
  </tranzakcio>
  <tranzakcio s_t="s1" v_t="v2">
    <datum>2022-09-11</datum>
  </tranzakcio>
  <tranzakcio s_t="s3" v_t="v2">
    <datum>2022-09-11</datum>
  </tranzakcio>
  <tranzakcio s_t="s5" v_t="v2">
    <datum>2022-03-05</datum>
  </tranzakcio>
  <tranzakcio s_t="s7" v_t="v3">
    <datum>2022-03-05</datum>
  </tranzakcio>
  <tranzakcio s_t="s8" v_t="v3">
    <datum>2022-05-25</datum>
  </tranzakcio>
  <tranzakcio s_t="s9" v_t="v3">
    <datum>2022-10-03</datum>
  </tranzakcio>
  <tranzakcio s_t="s10" v_t="v3">
    <datum>2022-10-03</datum>
  </tranzakcio>
  <tranzakcio s_t="s2" v_t="v3">
    <datum>2022-10-03</datum>
  </tranzakcio>
  <tranzakcio s_t="s4" v_t="v3">
    <datum>2022-10-09</datum>
  </tranzakcio>
  <tranzakcio s_t="s3" v_t="v3">
    <datum>2022-11-02</datum>
  </tranzakcio>
</NR_beadando>

=== NRobert-jmdrgg/JMDRGG_XMLgyak/XMLTaskJmdrgg/XMLjmdrgg.xml
<?xml version="1.0" encoding="UTF-8"?>

<NR_beadando xsi:noNamespaceSchemaLocation="XMLSchemaJmdrgg.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <cukraszda c_id="c1">
    <nev>Daubner Cukrászda</nev>
    <hely>
      <varos>Budapest</varos>
      <utca>Szépvölgyi </utca>
      <hazszam>50</hazszam>
    </hely>
    <ertekeles>4.3</ertekeles>
    <tulajdonos>Pista Laci</tulajdonos>
    <weboldal>daubnercukraszda.hu</weboldal>
  </cukraszda>
  <cukraszda c_id="c2">
    <nev>Frey Cukrászda</nev>
    <hely>
      <varos>Pécs</varos>
      <utca>Hungária</utca>
      <hazszam>53/1</hazszam>
    </hely>
    <ertekeles>4.7</ertekeles>
    <tulajdonos>Rotyis Bálint</tulajdonos>
    <weboldal>freycukraszda.hu</weboldal>
  </cukraszda>
  <cukraszda c_id="c3">
    <nev>Szűőke cukrászda</nev>
    <hely>
      <varos>Debrecen</varos>
      <utca>Úrrétje</utca>
      <hazszam>14</hazszam>
    </hely>
    <ertekeles>4.5</ertekeles>
    <tulajdonos>Szőke Balázs</tulajdonos>
    <weboldal>szokecukraszda.hu</weboldal>
  </cukraszda>

  <cukrasz cu_id="cu1" cu_c="c1">
    <nev>
      <vezeteknev>Tompa</vezeteknev>
      <keresztnev>Tamás</keresztnev>
    </nev>
    <eletkor>57</eletkor>
    <nem>férfi</nem>
  </cukrasz>
  <cukrasz cu_id="cu2" cu_c="c1">
    <nev>
      <vezeteknev>Patkós</vezeteknev>
      <keresztnev>Petra</keresztnev>
    </nev>
    <eletkor>21</eletkor>
    <nem>nő</nem>
  </cukrasz>
  <cukrasz cu_id="cu3" cu_c="c1">
    <nev>
      <vezeteknev>Nagy</vezeteknev>
      <keresztnev>Bence</keresztnev>
    </nev>
    <eletkor>18</eletkor>
    <nem>férfi</nem>
  </cukrasz>
  <cukrasz cu_id="cu4" cu_c="c2">
    <nev>
      <vezeteknev>Szabó</vezeteknev>
      <keresztnev>Bence</keresztnev>
    </nev>
    <eletkor>21</eletkor>
    <nem>férfi</nem>
  </cukrasz>
  <cukrasz cu_id="cu5" cu_c="c2">
    <nev>
      <vezeteknev>Mathers</vezeteknev>
      <keresztnev>Marshall</keresztnev>
    </nev>
    <eletkor>50</eletkor>
    <nem>férfi</nem>
  </cukrasz>
  <cukrasz cu_id="cu6" cu_c="c2">
    <nev>
      <vezeteknev>Jepsen</vezeteknev>
      <keresztnev>Carly</keresztnev>
    </nev>
    <eletkor>36</eletkor>
    <nem>nő</nem>
  </cukrasz>
  <cukrasz cu_id="cu7" cu_c="c3">
    <nev>
      <vezeteknev>Snake</vezeteknev>
      <keresztnev>David</keresztnev>
    </nev>
    <eletkor>24</eletkor>
    <nem>férfi</nem>
  </cukrasz>
  <cukrasz cu_id="cu8" cu_c="c3">
    <nev>
      <vezeteknev>McMillen</vezeteknev>
      <keresztnev>Edmund</keresztnev>
    </nev>
    <eletkor>42</eletkor>
    <nem>férfi</nem>
  </cukrasz>
  <cukrasz cu_id="cu9" cu_c="c3">
    <nev>
      <vezeteknev>Fors</vezeteknev>
      <keresztnev>Sebastian</keresztnev>
    </nev>
    <eletkor>31</eletkor>
    <nem>férfi</nem>
  </cukrasz>

  <sutemeny_lista sl_id="sl1" sl_c="c1">
    <legnepszerubb>Mignon</legnepszerubb>
    <legnepszerutlenebb>Almás pite</legnepszerutlenebb>
    <legutobb_frissitve>2022-04-26</legutobb_frissitve>
  </sutemeny_lista>
  <sutemeny_lista sl_id="sl2" sl_c="c2">
    <legnepszerubb>Képviselőfánk</legnepszerubb>
    <legnepszerutlenebb>Piskótatekercs</legnepszerutlenebb>
    <legutobb_frissitve>2022-06-22</legutobb_frissitve>
  </sutemeny_lista>
  <sutemeny_lista sl_id="sl3" sl_c="c3">
    <legnepszerubb>Joghurtos epertorta szelet</legnepszerubb>
    <legnepszerutlenebb>Somlói galuska</legnepszerutlenebb>
    <legutobb_frissitve>2022-03-20</legutobb_frissitve>
  </sutemeny_lista>


  <sutemeny s_id="s1" s_sl="sl1">
    <nev>Almás pite</nev>
    <ar>740</ar>
    <kaloria>296</kaloria>
    <tulajdonsag>klasszikus</tulajdonsag>
    <tulajdonsag>fahéjas</tulajdonsag>
    <tulajdonsag>almás</tulajdonsag>
    <tulajdonsag>pite</tulajdonsag>
  </sutemeny>
  <sutemeny s_id="s2" s_sl="sl1">
    <nev>Mandarinos túrótorta szelet</nev>
    <ar>990</ar>
    <kaloria>360</kaloria>
    <tulajdonsag>csokoládés piskóta</tulajdonsag>
    <tulajdonsag>gyümölcsös</tulajdonsag>
    <tulajdonsag>klasszikus tortaszelet</tulajdonsag>
    <tulajdonsag>tejszínes</tulajdonsag>
    <tulajdonsag>torta szelet</tulajdonsag>
    <tulajdonsag>túrós</tulajdonsag>
  </sutemeny>
  <sutemeny s_id="s3" s_sl="sl1">
    <nev>Cukormentes málnatorta szelet</nev>
    <ar>860</ar>
    <kaloria>200</kaloria>
    <tulajdonsag>Cukormentes </tulajdonsag>
    <tulajdonsag>málnás</tulajdonsag>
    <tulajdonsag>Mandulás</tulajdonsag>
    <tulajdonsag>piskóta</tulajdonsag>
    <tulajdonsag>torta szelet</tulajdonsag>
  </sutemeny>
  <sutemeny s_id="s4" s_sl="sl1">
    <nev>Mignon</nev>
    <ar>720</ar>
    <kaloria>120</kaloria>
    <tulajdonsag>cukormáz</tulajdonsag>
    <tulajdonsag>édes</tulajdonsag>
    <tulajdonsag>Hagyományos</tulajdonsag>
  </sutemeny>
  <sutemeny s_id="s5" s_sl="sl2">
    <nev>Piramis szelet</nev>
    <ar>850</ar>
    <kaloria>110</kaloria>
    <tulajdonsag>krém</tulajdonsag>
    <tulajdonsag>Csokoládés</tulajdonsag>
    <tulajdonsag>édes</tulajdonsag>
    <tulajdonsag>Klasszikus</tulajdonsag>
    <tulajdonsag>krémes</tulajdonsag>
    <tulajdonsag>piskóta</tulajdonsag>
  </sutemeny>
  <sutemeny s_id="s6" s_sl="sl2">
    <nev>Képviselőfánk</nev>
    <ar>790</ar>
    <kaloria>200</kaloria>
    <tulajdonsag>édes</tulajdonsag>
    <tulajdonsag>Klasszikus</tulajdonsag>
    <tulajdonsag>tejszínhabos</tulajdonsag>
    <tulajdonsag>vanília krémes</tulajdonsag>
  </sutemeny>
  <sutemeny s_id="s7" s_sl="sl2">
    <nev>Piskótatekercs</nev>
    <ar>710</ar>
    <kaloria>110</kaloria>
    <tulajdonsag>baracklekvár</tulajdonsag>
    <tulajdonsag>édes</tulajdonsag>
    <tulajdonsag>Klasszikus</tulajdonsag>
    <tulajdonsag>piskóta</tulajdonsag>
    <tulajdonsag>tekercs</tulajdonsag>
  </sutemeny>
  <sutemeny s_id="s8" s_sl="sl3">
    <nev>Málnahabos</nev>
    <ar>710</ar>
    <kaloria>230</kaloria>
    <tulajdonsag>édes</tulajdonsag>
    <tulajdonsag>gyümölcsös</tulajdonsag>
    <tulajdonsag>habos</tulajdonsag>
    <tulajdonsag>málnás</tulajdonsag>
  </sutemeny>
  <sutemeny s_id="s9" s_sl="sl3">
    <nev>Joghurtos epertorta szelet</nev>
    <ar>990</ar>
    <kaloria>400</kaloria>
    <tulajdonsag>édes</tulajdonsag>
    <tulajdonsag>epres</tulajdonsag>
    <tulajdonsag>gyümölcsös</tulajdonsag>
    <tulajdonsag>klasszikus</tulajdonsag>
    <tulajdonsag>piskóta</tulajdonsag>
    <tulajdonsag>tejszihabos</tulajdonsag>
    <tulajdonsag>torta szelet</tulajdonsag>
  </sutemeny>
  <sutemeny s_id="s10" s_sl="sl3">
    <nev>Somlói galuska</nev>
    <ar>1100</ar>
    <kaloria>450</kaloria>
    <tulajdonsag>csokoládé öntet</tulajdonsag>
    <tulajdonsag>Csokoládés</tulajdonsag>
    <tulajdonsag>mazsolás</tulajdonsag>
    <tulajdonsag>piskóta</tulajdonsag>
    <tulajdonsag>tejszínhabos</tulajdonsag>
  </sutemeny>

  <vasarlo v_id="v1">
    <nev>
      <vezeteknev>Nagy</vezeteknev>
      <keresztnev>Róbert</keresztnev>
    </nev>
    <torzsvasarlo>igen</torzsvasarlo>
    <eletkor>21</eletkor>
    <nem>férfi</nem>
  </vasarlo>
  <vasarlo v_id="v2">
    <nev>
      <vezeteknev>Sándor</vezeteknev>
      <keresztnev>Béla</keresztnev>
    </nev>
    <torzsvasarlo>nem</torzsvasarlo>
    <eletkor>26</eletkor>
    <nem>nő</nem>
  </vasarlo>
  <vasarlo v_id="v3">
    <nev>
      <vezeteknev>Ferenc</vezeteknev>
      <keresztnev>Viktor</keresztnev>
    </nev>
    <torzsvasarlo>nem</torzsvasarlo>
    <eletkor>56</eletkor>
    <nem>férfi</nem>
  </vasarlo>

  <tranzakcio v_t="v1" s_t="s1">
    <datum>2022-03-20</datum>
  </tranzakcio>
  <tranzakcio v_t="v1" s_t="s2">
    <datum>2022-03-20</datum>
  </tranzakcio>
  <tranzakcio v_t="v1" s_t="s4">
    <datum>2022-04-01</datum>
  </tranzakcio>
  <tranzakcio v_t="v1" s_t="s5">
    <datum>2022-04-01</datum>
  </tranzakcio>
  <tranzakcio v_t="v1" s_t="s9">
    <datum>2022-04-01</datum>
  </tranzakcio>
  <tranzakcio v_t="v2" s_t="s2">
    <datum>2022-04-12</datum>
  </tranzakcio>
  <tranzakcio v_t="v2" s_t="s1">
    <datum>2022-04-12</datum>
  </tranzakcio>
  <tranzakcio v_t="v2" s_t="s4">
    <datum>2022-05-02</datum>
  </tranzakcio>
  <tranzakcio v_t="v2" s_t="s1">
    <datum>2022-09-11</datum>
  </tranzakcio>
  <tranzakcio v_t="v2" s_t="s3">
    <datum>2022-09-11</datum>
  </tranzakcio>
  <tranzakcio v_t="v2" s_t="s5">
    <datum>2022-03-05</datum>
  </tranzakcio>
  <tranzakcio v_t="v3" s_t="s7">
    <datum>2022-03-05</datum>
  </tranzakcio>
  <tranzakcio v_t="v3" s_t="s8">
    <datum>2022-05-25</datum>
  </tranzakcio>
  <tranzakcio v_t="v3" s_t="s9">
    <datum>2022-10-03</datum>
  </tranzakcio>
  <tranzakcio v_t="v3" s_t="s10">
    <datum>2022-10-03</datum>
  </tranzakcio>
  <tranzakcio v_t="v3" s_t="s2">
    <datum>2022-10-03</datum>
  </tranzakcio>
  <tranzakcio v_t="v3" s_t="s4">
    <datum>2022-10-09</datum>
  </tranzakcio>
  <tranzakcio v_t="v3" s_t="s3">
    <datum>2022-11-02</datum>
  </tranzakcio>
</NR_beadando>
