=== NRobert-jmdrgg/JMDRGG_XMLgyak/jmdrgg_0928/NR_kurzusfelvetel.dtd
<!ATTLIST NR_kurzusfelvetel tanev CDATA #REQUIRED>
<!ATTLIST NR_kurzusfelvetel egyetem CDATA #REQUIRED>
<!ELEMENT NR_kurzusfelvetel (hallgato, kurzusok)>

<!ATTLIST hallgato id ID #REQUIRED>
<!ELEMENT hallgato (hnev, szulev, szak)>
<!ELEMENT hnev (#PCDATA)>
<!ELEMENT szulev (#PCDATA)>
<!ATTLIST szak evf CDATA #REQUIRED>
<!ELEMENT szak (#PCDATA)>

<!ATTLIST kurzus id ID #REQUIRED>
<!ATTLIST kurzus jovahagyas (igen | nem) "nem">
<!ELEMENT kurzusok (kurzus*)>
<!ELEMENT kurzus (kurzusnev, kredit, hely, idopont+, (oktato|oraado)?)>
<!ELEMENT kurzusnev (#PCDATA)>
<!ELEMENT kredit (#PCDATA)>
<!ELEMENT hely (#PCDATA)>
<!ELEMENT idopont (#PCDATA)>
<!ELEMENT oktato (#PCDATA)>
<!ELEMENT oraado (#PCDATA)>

=== NRobert-jmdrgg/JMDRGG_XMLgyak/jmdrgg_0928/NR_kurzusfelvetel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NR_kurzusfelvetel SYSTEM "./NR_kurzusfelvetel.dtd">

<NR_kurzusfelvetel tanev="2022/2023" egyetem="ME">
  <hallgato id="JMDRGG">
    <hnev>Nagy Róbert</hnev>
    <szulev>2001-03-20</szulev>
    <szak evf="5">Programtervező informatikus</szak>
  </hallgato>
  <kurzusok>
    <kurzus id="GEIAL331-B">
      <kurzusnev>Web technológiák 1.</kurzusnev>
      <kredit>5</kredit>
      <hely>XXX</hely>
      <idopont>Hétfő 08:00 - 10:00</idopont>
      <oktato>Agárdi Anita</oktato>
    </kurzus>
    <kurzus id="GEIAK130-B">
      <kurzusnev>Mesterséges intelligencia alapok</kurzusnev>
      <kredit>5</kredit>
      <hely>II</hely>
      <idopont>Kedd 09:00 - 12:00</idopont>
      <oktato>Kunné Dr. Tamás Judit</oktato>
    </kurzus>
    <kurzus id="GEIAL332-B">
      <kurzusnev>Adatkezelés XML-ben</kurzusnev>
      <kredit>5</kredit>
      <hely>XXXII</hely>
      <idopont>Kedd 12:00 - 14:00</idopont>
      <oktato>Dr. Bednarik László</oktato>
    </kurzus>
    <kurzus id="GEMAK121M">
      <kurzusnev>Algoritmusok és vizsgálat</kurzusnev>
      <kredit>5</kredit>
      <hely>X</hely>
      <idopont>Kedd 14:00 - 16:00</idopont>
      <oktato>Dr. Házy Attila</oktato>
    </kurzus>
    <kurzus id="GEIAL315-B">
      <kurzusnev>Vállalati információs rendszerek</kurzusnev>
      <kredit>5</kredit>
      <hely>In/103 </hely>
      <idopont>Szerda 16:00 - 18:00</idopont>
      <oktato>Dr. Sasvári Péter</oktato>
    </kurzus>
  </kurzusok>
</NR_kurzusfelvetel>
